import { jsPDF } from 'jspdf';

export function generateCertificate(
  userName: string,
  courseTitle: string,
  completionDate: string
): jsPDF {
  const doc = new jsPDF('landscape', 'mm', 'a4');
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const borderMargin = 10;
  doc.setDrawColor(22, 163, 74);
  doc.setLineWidth(3);
  doc.rect(
    borderMargin,
    borderMargin,
    pageW - borderMargin * 2,
    pageH - borderMargin * 2
  );

  doc.setDrawColor(22, 163, 74);
  doc.setLineWidth(0.5);
  doc.rect(
    borderMargin + 5,
    borderMargin + 5,
    pageW - borderMargin * 2 - 10,
    pageH - borderMargin * 2 - 10
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(36);
  doc.setTextColor(22, 163, 74);
  doc.text('Certificate of Completion', pageW / 2, 50, {
    align: 'center',
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text('This certifies that', pageW / 2, 75, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(30);
  doc.text(userName, pageW / 2, 100, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text(
    'has successfully completed the course',
    pageW / 2,
    120,
    { align: 'center' }
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(22, 163, 74);
  doc.text(courseTitle, pageW / 2, 145, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Date of completion: ${completionDate}`, pageW / 2, 175, {
    align: 'center',
  });

  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text(
    'This certificate is auto-generated by PhysioAI Online',
    pageW / 2,
    200,
    { align: 'center' }
  );

  return doc;
}
